import Dishwashing from "../components/images/supermarket/Dishwashing.png";
import Laundry from "../components/images/supermarket/Laundry.png";
import Cleaning from "../components/images/supermarket/Cleaning.png";
import Fresheners from "../components/images/supermarket/AirFresheners.png";
import BathroomCleaners from "../components/images/supermarket/BathroomCleaners.png";
import GlassCleaners from "../components/images/supermarket/GlassCleaners.png";
import KitchenCleaners from "../components/images/supermarket/KitchenCleaners.png";
import Disinfectants from "../components/images/supermarket/Disinfectants.png";
import Tissues from "../components/images/supermarket/Tissues.png";
import DisposableCups from "../components/images/supermarket/DisposableCups.png";
import DisposableFood from "../components/images/supermarket/DisposableFood.png";
import DisposablePlate from "../components/images/supermarket/DisposablePlate.png";



import Velveta from "../components/images/supermarket/Velveta.jpg";
import Tissues2 from "../components/images/supermarket/Tissues2.jpg";
import Frida from "../components/images/supermarket/Frida.jpg";
import Bahibowder from "../components/images/supermarket/Bahibowder.jpg";
import Clorox from "../components/images/supermarket/Clorox.jpg";
import TowelSet from "../components/images/supermarket/TowelSet.jpg";
import FilmPaper from "../components/images/supermarket/Film Paper.jpg";
import GarbageBags from "../components/images/supermarket/GarbageBags.jpg";
import SmallAirFryer from "../components/images/supermarket/Small Air Fryer.jpg";
import GlassCleaner from "../components/images/supermarket/Brix Lemon glass cleaner.jpg";
import ComfortFabric from "../components/images/supermarket/Comfort Fabric.jpg";
import Wipes from "../components/images/supermarket/White Shoe Wipes.jpg";
import MultipurposeWipes from "../components/images/supermarket/MultipurposeWipes .jpg";
import BrixToilet from "../components/images/supermarket/Brix Toilet.jpg";
import CoverFood from "../components/images/supermarket/Cover Food.jpg";


export const Data = [
  {
    "id": 1,
    "hyper": "WOMAN'S FASHION",
    "class": "links",
    "link1": "Tops & blouses",
    "link2": "Dresses & Jumpsuits",
    "link3": "Shorts & Skirts ",
    "link4": "Pants & Jeans",
    "link5": "Home Wear & Lingerie",
    "link6": "Jewelry & Watches ",
    "link7": "Handbags & Wallets",
    "link8": "Swimsuits Coverups",
    "link9": "Sports Wear",
    "link10": "Sunglasses",
    "link11": "Socks ",
    "link12": "Scarves",
    "link13": "Pullovers & Cardigans",
    "link14": "Jackets & Coats",
    "link15": "Hoodies & Sweatshirts",
  },
  {
    "id": 2,
    "hyper": "MEN'S FASHION",
    "class": "links",
    "link1": "Shirts",
    "link2": "T-shirts & Polos",
    "link3": "Pants",
    "link4": "Homewear & Underwear",
    "link5": "Swimsuits & Shorts",
    "link6": "Sports Wear",
    "link7": "Accessories",
    "link8": "Socks ",
    "link9": "Watches",
    "link10": "Suits",
    "link11": "Pullovers & Cardigans",
    "link12": "Jackets & Coats",
    "link13": "Hoodies & Sweatshirts",
  },
  {
    "id": 3,
    "hyper": "WOMAN'S SHOES",
    "class": "links",
    "link1": "Sneakers",
    "link2": "Heels",
    "link3": "Flats & Loafers",
    "link4": "Slippers & Sandals",
  },
  {
    "id": 4,
    "hyper": "MEN'S SHOES",
    "class": "links2",
    "link1": "Sneakers",
    "link2": "Casual & Loafers",
    "link3": "Slippers & Sandals",
    "link4": "Formal Shoes",
  },
  {
    "id": 5,
    "hyper": "KID'S FASHION",
    "class": "links3",
    "link1": "Boy's Fashion",
    "link2": "Girl's Fashion",

  },
  {
    "id": 6,
    "hyper": "BABY FASHION",
    "class": "links4",
    "link1": "Boy's Clothes & Shoes ",
    "link2": "Girl's Clothes & Shoes",

  },
]
export const Data2 = [
  {
    "id": 1,
    "hyper": "PERSONAL CARE",
    "class": "links",
    "link1": "Oral Care",
    "link2": "Feminine Care",
    "link3": "Shave & Hair Removal ",
    "link4": "Deodorants",
    "link5": "Shower Gels ",
    "link6": "Face Wash ",
  },
  {
    "id": 2,
    "hyper": "HAIR CARE",
    "class": "links",
    "link1": "Styling Tools & Appliances",
    "link2": "Hair Styling Products",
    "link3": "Shampoo, Conditioner & Serums",
    "link4": "Hair Coloring",
    "link5": "Extensions & Wigs",
    "link6": "Hair Accessories",
  },

  {
    "id": 3,
    "hyper": "FRAGRANCE",
    "class": "links",
    "link1": " Women's Perfumes & Body Splashes",
    "link2": "Men's Perfumes",
    "link3": "Children's Perfumes",
  },
  {
    "id": 4,
    "hyper": "SKIN CARE",
    "class": "links5",
    "link1": "Body",
    "link2": "Eyes",
    "link3": "Face",
    "link4": "Feet & Hands",
    "link5": "Sunscreens & Tanning oils",
  },
  {
    "id": 5,
    "hyper": "HEALTH CARE",
    "class": "links5",
    "link1": "Wellness & Relaxation",
    "link2": "Sexual Wellness",
    "link3": "Medical Supplies & Equipment",
    "link4": "Contact Lenses & Solutions",
  },
  {
    "id": 6,
    "hyper": "MAKEUP",
    "class": "links6",
    "link1": "Face Makeup",
    "link2": "Lip Makeup",
    "link3": "Eye Makeup",
    "link4": "Makeup Remover",
    "link5": "Makeup Brushes & Tools",
    "link6": "Nails",
  },
]

export const Data3 = [
  {
    "id": 1,
    "hyper": "DIAPERING",
    "class": "links",
    "link1": "Disposable Diapers",
    "link2": "Wipes & Holders",
    "link3": "Diaper Bags ",
  },
  {
    "id": 2,
    "hyper": "BATHING & SKIN CARE",
    "class": "links",
    "link1": "Lotions",
    "link2": "Shampoo & Conditioner",
    "link3": "Bath Essentials",
    "link4": "Grooming & Healthcare Kits",
    "link5": "Potty Training",
    "link6": "Health & Baby Care",
  },
  {
    "id": 3,
    "hyper": "STROLLERS & ACCESSORIES",
    "class": "links",
    "link1": "Accessories",
    "link2": "Strollers",
    "link3": "Car Seats",
  },
  {
    "id": 4,
    "hyper": "BABY FEEDING",
    "class": "links6",
    "link1": "Bottle-Feeding & Tablewear",
    "link2": "Breast feeding",
    "link3": "Baby Food",
    "link4": "Bibs & Burp Cloths",
  },
  {
    "id": 5,
    "hyper": "BABY SAFETY",
    "class": "links5",
    "link1": "Kitchen Safety",
    "link2": "Outdoor Safety",
  },

  {
    "id": 6,
    "hyper": "TOYS & GAMES",
    "class": "links6",
    "link1": "Baby & Toddler Toys",
    "link2": "Dolls & Accessories",
    "link3": "Learning & Education",
    "link4": "Action Figures & Statues",
    "link5": "Arts & Crafts",
    "link6": "Dress Up & Pretend Play",
    "link7": "Puzzles",
    "link8": "Toy Remote Control & Play Vehicles",
  },
  {
    "id": 7,
    "hyper": "NURSERY",
    "class": "links7",
    "link1": "Beds, Cribs & Bedding",
    "link2": "Beds, Cribs & Bedding",
  },
  {
    "id": 8,
    "hyper": "GEAR",
    "class": "links8",
    "link1": "Swings, Jumpers & Bouncers",
    "link2": "Backpacks & Carriers",
    "link3": "Walkers",
  },
]

export const Data4 = [
  {
    "id": 1,
    "hyper": "MOBILE PHONES",
    "class": "links",
    "link1": "Smartphones",
    "link2": "Cell Phones",
  },
  {
    "id": 2,
    "hyper": "MOBILE PHONES ACCESSORIES",
    "class": "links",
    "link1": "Phone Cases",
    "link2": "Screen Protectors",
    "link3": "Bluetooth Headsets",
    "link4": "Headsets",
    "link5": "Cables",
    "link6": "Portable Power Banks",
    "link7": "Smart Watches",
    "link8": "Smart Watches Accessories",
    "link9": "Memory Cards",
    "link10": "Chargers",
    "link11": "Car Accessories",
    "link12": "Mounts & Stands",
    "link13": "Selfie Sticks & Tripods",
  },
  {
    "id": 3,
    "hyper": "TABLETS",
    "class": "links",
    "link1": "Tablets",
    "link2": "Educational Tablets",
    "link3": "Tablet Accessories",

  },
]

export const Data5 = [
  {
    "id": 1,
    "hyper": "HOME ESSENTIALS",
    "class": "links",
    "link1": "Home Decor",
    "link2": "Lighting",
    "link3": "Bedding",
    "link4": "Bath",
    "link5": "Storage & Organization",
    "link6": "Cleaning Supplies",
    "link7": "Event & Party Supplies",
    "link8": "Seasonal Decor",
    "link9": "Light Blubs ",
    "link10": "Power & Hand Tools",
    "link11": "Air Purifiers",
    "link12": "Tools & Improvements",
  },
  {
    "id": 2,
    "hyper": "FURNITURE",
    "class": "links",
    "link1": "Living room",
    "link2": "Bedroom Furniture",
    "link3": "Dining room",
    "link4": "Bean Bags",
    "link5": "TV Units",
    "link6": "Storage Units",
  },
  {
    "id": 3,
    "hyper": "GARDEN & OUTDOORS",
    "class": "links",
    "link1": "Outdoor Decor",
    "link2": "Outdoor Furniture & Accessories",
    "link3": "Grills & Outdoor Cooking",
    "link4": "Gardening & Lawn Care",
    "link5": "Pest Control Repellents ",
    "link6": "Artificial Plants",
  },
  {
    "id": 4,
    "hyper": "KITCHEN & DINING",
    "class": "links9",
    "link1": "Cookware",
    "link2": "Bakeware",
    "link3": "Serveware",
    "link4": "Glassware",
    "link5": "Kitchen Utensils",
    "link6": "Kitchen Storage",
  },
  {
    "id": 5,
    "hyper": "SCHOOL & OFFICE SUPPLIES",
    "class": "links10",
    "link1": "School & Office Furniture",
    "link2": "Stationary & Supplies",

  },
]

export const Data6 = [
  {
    "id": 1,
    "hyper": "COOKING APPLIANCES",
    "class": "links",
    "link1": "Air Fryers",
    "link2": "Food Processors",
    "link3": "Microwaves",
    "link4": "Blenders",
    "link5": "Mixers",
    "link6": "Choppers",
    "link7": "Hand Blenders",
    "link8": "Kettles",
    "link9": "Coffee Machine ",
    "link10": "Waffle & Sandwich Makers",
    "link11": "Ovens & Toasters",
  },
  {
    "id": 2,
    "hyper": "Home Appliances",
    "class": "links",
    "link1": "Refrigerators",
    "link2": "Freezers",
    "link3": "Dishwashers",
    "link4": "Washers & Dryers",
    "link5": "Vacuums & Floor Care",
    "link6": "Cookers",
    "link7": "Irons & Steamers",
    "link8": "Cook Top",
    "link9": "Window Fans",
    "link10": "Range Hoods",
    "link11": "Hot Plate",
  },
  {
    "id": 3,
    "hyper": "COOLING & HEATING  APPLIANCES",
    "class": "links",
    "link1": "Air conditioners",
    "link2": "Household Fans",
    "link3": "Water Dispensers ",
    "link4": "Water Heaters",
    "link5": "Heaters",
    "link6": "Water Coolers & Filters",
  }
]
export const Data7 = [
  {
    "id": 1,
    "hyper": "Televisions & Receivers",
    "class": "links",
    "link1": "Televisions",
    "link2": "Receivers",
    "link3": "Remote Controls",

  },
  {
    "id": 2,
    "hyper": "AUDIO",
    "class": "links11",
    "link1": " Radios",
    "link2": "Audio Speakers",
    "link3": "Home Theater Systems",
    "link4": "Headphones",
  },
]
export const Data8 = [
  {
    "id": 1,
    "hyper": "DESKTOP & LAPTOPS",
    "class": "links",
    "link1": "2 in 1 Laptops",
    "link2": "Gaming Laptops",
    "link3": "Traditional Laptops",
    "link4": "Macbooks",
    "link5": "Desktops",
    "link6": "Monitors",
  },
  {
    "id": 2,
    "hyper": "COMPUTER COMPONENTS",
    "class": "links",
    "link1": "Internal Hard Drives",
    "link2": "Graphics Cards",
    "link3": "Fans & Cooling",
    "link4": "Audio & Video Accessories",
    "link5": "Computer Cable Adapters",
    "link6": "Keyboard",
    "link7": "Mouse",
    "link8": "USB Gadgets",
  },
  {
    "id": 3,
    "hyper": "NETWORKING PRODUCTS",
    "class": "links",
    "link1": "Network Adapters",
    "link2": "Routers",
    "link3": "Wireless Access Points",
    "link4": "Network Switches",
  },
  {
    "id": 4,
    "hyper": "DATA STORAGE",
    "class": "links12",
    "link1": "USB Flash Drives",
    "link2": "External Hard Drives",
  },
  {
    "id": 5,
    "hyper": "PRINTERS & SCANNERS",
    "class": "links13",
    "link1": "Printers",
    "link2": "Scanners",
    "link3": "Printer Ink & Toner",
  },
  {
    "id": 6,
    "hyper": "COMPUTER & ACCESSORIES",
    "class": "links7",
    "link1": "Laptop Accessories",
  },
]
export const Data9 = [
  {
    "id": 1,
    "hyper": "CAEDIO TRAINING",
    "class": "links",
    "link1": "Treadmills",
    "link2": "Exercise Bike",
    "link3": "Elliptical Trainers",
  },
  {
    "id": 2,
    "hyper": "SPORTS WEAR",
    "class": "links",
    "link1": "Men Sports Wear",
    "link2": "Women Sports Wear",
  },
  {
    "id": 3,
    "hyper": "ACCESSORIES",
    "class": "links",
    "link1": "Exercise Bands",
    "link2": "Jump Ropes",
    "link3": "Exercise Mats",
    "link4": "Gym Bags",

  },
  {
    "id": 4,
    "hyper": "STRENGTH TRAINING EQUIPMENT",
    "class": "links6",
    "link1": "Dumbbells",
    "link2": "Bars",
    "link3": "Core & Abdominal Trainers",

  },
  {
    "id": 5,
    "hyper": "SPORTS & FITNESS",
    "class": "links6",
    "link1": "Accessories",
    "link2": "Swimming",
    "link3": "Team Sports",
    "link4": "Hunting & Fishing",
    "link5": "Leisure Sports & Game Room",
  },
  {
    "id": 6,
    "hyper": "OUTDOOR & ADVENTURE",
    "class": "links14",
    "link1": "Cycling",
    "link2": "Running",
  }
]
export const Data10 = [
  {
    "id": 1,
    "hyper": "PLAYSTATION 5",
    "class": "links",
    "link1": "Consoles",
    "link2": "Games",
    "link3": "Controllers",
    "link4": "Cards",
    "link5": "Accessories",
  },
  {
    "id": 2,
    "hyper": "XBOX",
    "class": "links",
    "link1": "Controllers",
    "link2": "Accessories",
  },
  {
    "id": 3,
    "hyper": "CARD & BOARD GAMES",
    "class": "links",
    "link1": "Card Games",
    "link2": "Board Games",
  },
  {
    "id": 4,
    "hyper": "PLAYSTATION 4",
    "class": "links10",
    "link1": "Games",
    "link2": "Controllers",
    "link3": "Cards",
    "link4": "Accessories",
  },
  {
    "id": 5,
    "hyper": "PC GAMING",
    "class": "links8",
    "link1": "Gaming Laptops",
    "link2": "Headsets",
    "link3": "Keyboards",
    "link4": "Mouse",
    "link5": "Gaming Chairs",
    "link6": "Monitors",

  },
]
export const Data11 = [
  {
    "id": 1,
    "hyper": "ELECTRONICS",
    "class": "links",
    "link1": "Television & Video",
    "link2": "Cameras",
    "link3": "Audio",
  },
  {
    "id": 2,
    "hyper": "HAND CRAFTED",
    "class": "links",
    "link1": "Women Accessories",
    "link2": "Baby Products",
    "link3": "Bags",
    "link4": "Bedding",
    "link5": "Home Décor",
    "link6": "Jewelry & Accessories",
  },
  {
    "id": 3,
    "hyper": "BOOKS, MOVIES AND MUSIC",
    "class": "links",
    "link1": "Art & Humanities",
    "link2": "Bestselling Books",
    "link3": "Biography & Autobiography Books",
    "link4": "Business & Finance Books",
    "link5": "Education & Learning",
    "link6": "Entertainment Books",
    "link7": "Family & Lifestyle Books",
    "link8": "Fiction Books",
    "link9": "Journals & Planners",
    "link10": "Magazines",
    "link11": "Motivational & Self-Help Books",
    "link12": "Religion Books",
    "link13": "Science & Technology Books",
  },
  {
    "id": 4,
    "hyper": "Automobile",
    "class": "links6",
    "link1": "Car Care",
    "link2": "Car Electronics & Lights",
    "link3": "Oils & Fluids",
    "link4": "Exterior Accessories",
    "link5": "Interior Accessories",
  },
  {
    "id": 5,
    "hyper": "Industrial & Scientific",
    "class": "links15",
    "link1": "Packaging & Shipping Supplies",
  },
]

export const Sec1 = [
  {
    "id": 1,
    "link": "/Dishwashing",
    "image": Dishwashing,
  },
  {
    "id": 2,
    "link": "/Laundry",
    "image": Laundry,
  },
  {
    "id": 3,
    "link": "/Cleaning",
    "image": Cleaning,
  },
  {
    "id": 4,
    "link": "/AirFresheners",
    "image": Fresheners,
  },
  {
    "id": 5,
    "link": "/BathroomCleaners",
    "image": BathroomCleaners,
  },
  {
    "id": 6,
    "link": "/GlassCleaners",
    "image": GlassCleaners,
  },
]

export const Sec2 = [
  {
    "id": 1,
    "link": "/KitchenCleaners",
    "image": KitchenCleaners,
  },
  {
    "id": 2,
    "link": "/Disinfectants",
    "image": Disinfectants,
  },
  {
    "id": 3,
    "link": "/Tissues",
    "image": Tissues,
  },
  {
    "id": 4,
    "link": "/DisposableCups",
    "image": DisposableCups,
  },
  {
    "id": 5,
    "link": "/DisposableFood",
    "image": DisposableFood,
  },
  {
    "id": 6,
    "link": "/DisposablePlate",
    "image": DisposablePlate,
  },
]

export const Sec3 = [
  {
    "id": 1,
    "image": Velveta,
    'alt': "Velveta",
    "sale": "-24%",
    "title": "Velveta Fabric Softener & Freshener Gel - Romance scent- 350 ml",
    "price": "EGP 34.00",
    "befor": "EGP 45.00",
  },
  {
    "id": 2,
    "image": Tissues2,
    'alt': "Tissues",
    "title": "White Mega Pack 500 Tissues Set Of 6, White",
    "price": "EGP 199.00",
    "befor": "",
  },
  {
    "id": 3,
    "image": Frida,
    'alt': "Frida",
    "sale": "-25%",
    "title": "Frida Home Cleaning Fragrance sahra 480 ml",
    "price": "EGP 38.00",
    "befor": "EGP 51.00",
  },
  {
    "id": 4,
    "image": Bahibowder,
    'alt': "Bahibowder",
    "sale": "-22%",
    "title": "Bahi Powder Lavander - 1 Kg",
    "price": "EGP 47.00",
    "befor": "EGP 60.00",
  },
  {
    "id": 5,
    "image": Clorox,
    'alt': "Clorox",
    "sale": "-27%",
    "title": "Clorox 5x1 Disinfecting Household Cleaner Pine 700ML",
    "price": "EGP 44.00",
    "befor": "EGP 60.00",
  },
  {
    "id": 6,
    "image": TowelSet,
    'alt': "TowelSet",
    "sale": "-69%",
    "title": "Towel Set, Towels For Bathroom, Kitchen, 5 Pcs.",
    "price": "EGP 47.00",
    "befor": "EGP 150.00",
  },
  {
    "id": 7,
    "image": FilmPaper,
    'alt': "Film Paper",
    "sale": "-28%",
    "title": "Sanita Premium Cling Film Paper Food Wraps - 30 Meters",
    "price": "EGP 47.00",
    "befor": "EGP 65.00",
  },
  {
    "id": 8,
    "image": GarbageBags,
    'alt': "GarbageBags",
    "sale": "-23%",
    "title": "Heavy Garbage Bags - By Weight, 1 Kg - Size 70 X 50 Cm",
    "price": "EGP 54.00",
    "befor": "EGP 70.00",
  },
  {
    "id": 9,
    "image": SmallAirFryer,
    'alt': "Small Air Fryer",
    "sale": "-13%",
    "title": "Small Air Fryer Silicone Pot",
    "price": "EGP 69.99",
    "befor": "EGP 80.00",
  },
  {
    "id": 10,
    "image": GlassCleaner,
    'alt': "Brix Lemon glass cleaner",
    "sale": "-25%",
    "title": "Brix Lemon glass cleaner - 500ml",
    "price": "EGP 27.00",
    "befor": "EGP 35.80",
  },
  {
    "id": 11,
    "image": ComfortFabric,
    'alt': "Comfort Fabric Softener",
    "sale": "-32%",
    "title": "Comfort Fabric Softener Flora Soft Pink 1 Liter Promo",
    "price": "EGP 73.00",
    "befor": "EGP 108.00",
  },
  {
    "id": 12,
    "image": Wipes,
    'alt': "White Shoe Wipes",
    "sale": "-23%",
    "title": "White Shoe Wipes - 20 Wipes -4Pacs",
    "price": "EGP 115.00",
    "befor": "EGP 150.00",
  },
  {
    "id": 13,
    "image": MultipurposeWipes,
    'alt': "MultipurposeWipes ",
    "sale": "-33%",
    "title": "White Antibacterial Multipurpose Wipes 6Pack * 50 Wipes",
    "price": "EGP 175.00",
    "befor": "EGP 260.00",
  },
  {
    "id": 14,
    "image": BrixToilet,
    'alt': "Brix Toilet",
    "sale": "-13%",
    "title": "Brix Toilet Cleaner Blue - 450 ML",
    "price": "EGP 39.50",
    "befor": "EGP 45.30",
  },
  {
    "id": 15,
    "image": CoverFood,
    'alt': "Cover Food",
    "sale": "-85%",
    "title": "Taha Offer Bags To Cover Food In The Refrigerator And Outside 50 Pieces Transparent Color",
    "price": "EGP 19.19",
    "befor": "EGP 125.00",
  },

]

